### ISSUE TITLE
ValueError: Output file name cannot contain '_' (see issue #20)

### ISSUE THREAD

**Issue by luigiScarso** [MonitoraPA/monitorapa#23]
Salve, seguendo le istruzioni in MANUALE.md ho una exception:
```
# python3 cli/check/browsing.py out/enti/2022-08-10/dataset.tsv
Traceback (most recent call last):
  File "cli/check/browsing.py", line 481, in <module>
    main(sys.argv)
  File "cli/check/browsing.py", line 477, in main
    run(dataset)
  File "cli/check/browsing.py", line 435, in run
    loadChecks(dataset, checksToRun)
  File "cli/check/browsing.py", line 411, in loadChecks
    addPythonCheck(dataset, checksToRun, '000_actual_url', checkActualUrl)
  File "cli/check/browsing.py", line 379, in addPythonCheck
    outputFile = check.outputFileName(dataset, 'browsing', name + '.tsv')
  File "/opt/monitorapa/./lib/check.py", line 72, in outputFileName
    raise ValueError("Output file name cannot contain '_' (see issue #20)")
ValueError: Output file name cannot contain '_' (see issue #20)

```
Sbaglio qualcosa ?

**Comment by Shamar** [comment]
Ciao @luigiScarso scusa il ritardo nella risposta...

in teoria il problema dovrebbe essere stato fixato in questa commit https://github.com/MonitoraPA/monitorapa/commit/afd87dc19c8703e2b7f50c433730d74c9664312b

hai voglia di riprovare?

**Comment by luigiScarso** [comment]
Si, ora è ok.
